### ISSUE TITLE
Version 3.5.0.3 not being picked up by SwiftPM

### ISSUE THREAD

**Issue by ptsochantaris** [AgoraIO/AgoraAudio_iOS#2]
It seems that the SPM version is stuck at 3.5.0 rather than 3.5.0.3. Would be nice to be able to have the memory leak and crash issues, that 3.5.x address, fixed on projects that use SPM as well.

**Comment by plutoless** [comment]
hi @ptsochantaris it's nice to receive your feedback and we will talk to release team and come back to you.

**Comment by plutoless** [comment]
@ptsochantaris 
![企业微信截图_16316741077489](https://user-images.githubusercontent.com/471561/133362258-6b0fbecc-abc3-4873-89ef-df37136ba9f3.png)
it has been uploaded already.

**Comment by plutoless** [comment]
feel free to reopen if needed

**Comment by ptsochantaris** [comment]
Hi, thanks for replying, but Xcode is still not picking anything up above 3.5.0. Is it just that the `.3` bit isn't reflected in the package manager and I'm just reading it wrong? This is a screenshot I just took after upgrading all the packages:

<img width="326" alt="Screenshot 2021-09-15 at 07 23 23" src="https://user-images.githubusercontent.com/521581/133381441-98e242ef-1ab9-4f65-92e3-6a2b511d7d8f.png">

**Comment by ptsochantaris** [comment]
Also, there's no re-open option for 3rd parties on this repo I think :) I hope you get to read this anyway.
