### ISSUE TITLE
Can you please help to resolve this warning? the target should not be set to v8 only

### ISSUE THREAD

**Issue by bytewayio** [AgoraIO/AgoraAudio_iOS#3]
.../SourcePackages/checkouts/AgoraAudio_iOS/Package.swift The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 15.2.99.

**Comment by maxxfrazer** [comment]
I'll pass this along to the deployment script maintainers. It will not cause any issues for your app, just a slightly annoying error message.
The SDK does run fine on iOS 8, just Xcode can no longer target it directly.

**Comment by bytewayio** [comment]
That's true, however, that blocks our build pipeline, which does not allow any warnings

**Comment by maxxfrazer** [comment]
use the latest patch update 3.6.1-r.2, otherwise 3.6.2 will be out next week that also has the fix

**Comment by bytewayio** [comment]
Nice, thanks!
