### ISSUE TITLE
SDK crash when join channel call

### ISSUE THREAD

**Issue by waseemwanologicalsolutions** [AgoraIO/AgoraAudio_iOS#7]
version 4.1.1
crash when join channel trying after initialization
tried using package manager and cocoapods

objc[1571]: Class HWDarwinResamplerImpl is implemented in both /private/var/containers/Bundle/Application/4A951530-9363-409F-B142-FC94491571BA/testAgora.app/Frameworks/AgoraRtcKit.framework/AgoraRtcKit (0x105fb1770) and /private/var/containers/Bundle/Application/4A951530-9363-409F-B142-FC94491571BA/testAgora.app/Frameworks/AgoraAudioBeautyExtension.framework/AgoraAudioBeautyExtension (0x10318d940). One of the two will be used. Which one is undefined.
objc[1571]: Class HWDarwinResamplerImpl is implemented in both /private/var/containers/Bundle/Application/4A951530-9363-409F-B142-FC94491571BA/testAgora.app/Frameworks/AgoraRtcKit.framework/AgoraRtcKit (0x105fb1770) and /private/var/containers/Bundle/Application/4A951530-9363-409F-B142-FC94491571BA/testAgora.app/Frameworks/AgoraSpatialAudioExtension.framework/AgoraSpatialAudioExtension (0x103a68d18). One of the two will be used. Which one is undefined.
2023-02-22 14:30:33.254746+0500 testAgora[1571:552834] [User Defaults] CFPrefsPlistSource<0x280bccb80> (Domain: kCFPreferencesAnyApplication, User: kCFPreferencesCurrentUser, ByHost: No, Container: (null), Contents Need Refresh: No): Value for key AppleLanguages was (
    "en-PK",
    "ur-PK"
). Expected (
    "en-AE",
    "ur-AE"
) (Preferences(420): 2022-08-01 17:51:31 (PKT))
AudioBeautyExtensionProvider::enumerateExtensions [extension_count:22]
<img width="1150" alt="Screenshot 2023-02-22 at 2 12 19 PM" src="https://user-images.githubusercontent.com/93919087/220590828-4018e3dc-cad5-466b-9fe3-85b9fe57c785.png">

<img width="1135" alt="Screenshot 2023-02-22 at 2 15 13 PM" src="https://user-images.githubusercontent.com/93919087/220590786-443f7de5-3900-42e4-b814-e2cf042775dc.png">

`    func initializeAgoraEngine() {
        let config = AgoraRtcEngineConfig()
        config.appId = AgoraCredentials.appID
        agoraEngine = AgoraRtcEngineKit.sharedEngine(with: config, delegate: self)
        self.perform(#selector(joinChannel), with: nil, afterDelay: 6)
    }
    
    @objc func joinChannel() async {
        if await !self.checkForPermissions() {
            showMessage(title: "Error", text: "Permissions were not granted")
            return
        }
        
        let option = AgoraRtcChannelMediaOptions()
        
        if self.userRole == .broadcaster {
            option.clientRoleType = .broadcaster
        } else {
            option.clientRoleType = .audience
        }
        
        option.channelProfile = .communication
        
        let result = agoraEngine.joinChannel(
            byToken: AgoraCredentials.token, channelId: AgoraCredentials.channelName, uid: 0, mediaOptions: option,
            joinSuccess: { (channel, uid, elapsed) in }
        )
        if (result == 0) {
            joined = true
            showMessage(title: "Success", text: "Successfully joined the channel as \(self.userRole)")
        }
    }`

**Comment by maxxfrazer** [comment]
sorry for the delay, is this still an issue for you?
