### ISSUE TITLE
Class HWDarwinResamplerImpl is implemented in both AgoraRtcKit and AgoraAudioBeautyExtension

### ISSUE THREAD

**Issue by YangWiwat** [AgoraIO/AgoraAudio_iOS#9]
After finishing building a quick iOS application based on the Voice Calling SDK quick start, a warning message consistently appears in the Debugger pane:

"objc[3465]: Class HWDarwinResamplerImpl is implemented in both AgoraRtcKit.framework/AgoraRtcKit 
and 
AgoraAudioBeautyExtension.framework/AgoraAudioBeautyExtension. 
One of the two will be used. Which one is undefined."

I am not sure if this is dangerous.

**Comment by maxxfrazer** [comment]
The core library of AgoraRtcKit has the classes with no functionality, and the beauty extension package has the functionality as overrides. So it wouldn't cause problems in this case, but it's not really the best practice on our part.
I'll pass this along to the SDK team, as it is annoying and would be better to do it another way in the future!
